config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :products
  root 'products#index'


  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }


end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  mount_uploader :image, ImageUploader
  has_many :comments
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.includes(:user).all
    @comment  = @product.comments.build(user_id: current_user.id) if current_user
    @user = User.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :stock, :note, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div class="alert alert-danger">
      <% product.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, id: :product_stock, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, id: :product_note, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <div class="text-right">
    <%= link_to 'キャンセル', products_path, class: 'btn btn-default' %>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1><%= Product.model_name.human %></h1>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1><%= Product.model_name.human %></h1>

<div class="text-right">
  <%= link_to '追加', new_product_path, class: 'btn btn-primary' %>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= Product.human_attribute_name :name %></th>
        <th><%= Product.human_attribute_name :price %></th>
        <th><%= Product.human_attribute_name :stock %></th>
        <th><%= Product.human_attribute_name :note %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.stock %></td>
          <td><%= product.note %></td>
          <td><%= link_to '表示', product, class: 'btn btn-default' %></td>
          <td><%= link_to '編集', edit_product_path(product), class: 'btn btn-default' %></td>
          <td><%= link_to '削除', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1><%= Product.model_name.human %></h1>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p>
  <strong><%= Product.human_attribute_name :name %>:</strong>
  <%= @product.name %>
</p>

<p>
  <strong><%= Product.human_attribute_name :price %>:</strong>
  <%= @product.price %>
</p>

<p>
  <strong><%= Product.human_attribute_name :stock %>:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong><%= Product.human_attribute_name :note %>:</strong>
  <%= @product.note %>
</p>

<p>
  <%= image_tag(@product.image_url) if @product.image.present? %>
</p>
<div class="text-right">
  <%= link_to 'Edit', edit_product_path(@product),class: 'btn btn-warning' %> 
  <%= link_to 'Back', products_path,class: 'btn btn-default' %>
</div>
this is the comment section
<div>
  <% @comments.each do |comment| %>
    <div>
      <blockquote>
        <p><%= comment.body %></p>
	<footer><%= comment.user_id %><%= @user.find_by(id: comment.user_id)['email'] %></footer>
      </blockquote>
      <% if user_signed_in? && comment.user == current_user %>
        <div class="text-right">  
          <p><%= link_to 'Delete this comment', comment_path(comment), method: :delete,class: 'btn btn-danger' %></p>
        </div>
        <% end %>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <%= render 'comments/form' %>
  <% end %>
</div>